/*
 * TimeLimit Copyright <C> 2019 - 2026 Jonas Lochmann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

plugins {
    id 'com.android.application' version '8.13.2' apply false
    id 'com.android.library' version '8.13.2' apply false
    id 'org.jetbrains.kotlin.android' version "2.2.10" apply false
    id 'org.jetbrains.kotlin.jvm' version "2.2.10" apply false
    id 'org.jetbrains.kotlin.plugin.compose' version "2.2.10" apply false
    id 'com.google.devtools.ksp' version '2.3.2' apply false
    id 'androidx.navigation.safeargs' version '2.9.7' apply false
    id 'com.squareup.wire' version '5.5.0' apply false
}